server:
  address: localhost
  port: 8080
database:
  type: postgres
  postgres:
    host: db
    port: 5432
    user: seedpod
    password: seedpod-password
    dbname: seedpod
    sslmode: disable
    timezone: Asia/Shanghai
debug: true