version: "3"

services:
  db:
    image: postgres:13.3
    container_name: db
    environment:
      POSTGRES_DB: seedpod
      POSTGRES_USER: seedpod
      POSTGRES_PASSWORD: seedpod-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U seedpod" ]
      interval: 10s
      timeout: 5s
      retries: 5


