version: "3"

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: seedpod
      POSTGRES_USER: seedpod
      POSTGRES_PASSWORD: seedpod-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U seedpod" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: seedpod:latest
    command: [ "/usr/local/bin/seedpod", "serve", "--config", "./config.yml" ]
    volumes:
      - ./config.yml:/config.yml
    ports:
      - 8080:8080
    depends_on:
      - db


